In [21]:
#Count the frequency of each letters in the sentence
sentence1 =" Mary had a little lamb €"
count = {}
for i in sentence1:
    print("{0} = {1}".format(i, ord(i)))
    if i in count:
        count[i.lower()] = count[i.lower()] + 1
    else:
        count[i.lower()] = 1
print(count)
print(count['m'])
print(chr(8364))

#Using List Comprehension
sentence1 =" Mary had a little lamb €"
char_count = { char : sentence1.count(char) for char in sentence1 }
print(char_count)

  = 32
M = 77
a = 97
r = 114
y = 121
  = 32
h = 104
a = 97
d = 100
  = 32
a = 97
  = 32
l = 108
i = 105
t = 116
t = 116
l = 108
e = 101
  = 32
l = 108
a = 97
m = 109
b = 98
  = 32
€ = 8364
{' ': 6, 'm': 2, 'a': 4, 'r': 1, 'y': 1, 'h': 1, 'd': 1, 'l': 3, 'i': 1, 't': 2, 'e': 1, 'b': 1, '€': 1}
2
€
{' ': 6, 'M': 1, 'a': 4, 'r': 1, 'y': 1, 'h': 1, 'd': 1, 'l': 3, 'i': 1, 't': 2, 'e': 1, 'm': 1, 'b': 1, '€': 1}


In [15]:
#Is Unique: Write Code to determine if a string has all unique characters
sentence1 = "Mary had a little lamb"
count = {}
for i in sentence1:
    if i in count:
        print("Duplicate letter found=",ord(i))
    else:
        count[i.lower()] = 1

Duplicate letter found= 97
Duplicate letter found= 32
Duplicate letter found= 97
Duplicate letter found= 32
Duplicate letter found= 116
Duplicate letter found= 108
Duplicate letter found= 32
Duplicate letter found= 108
Duplicate letter found= 97
Duplicate letter found= 109


In [10]:
#Activity Selection Problem
#start[]  =  {5, 14, 21};
#finish[] =  {20, 26, 35};
#start  =  [1, 3, 0, 5, 8, 5]
#finish =  [2, 4, 6, 7, 9, 9] 
def activity(s, f):
    fin = f[0]
    print (0)
    for i in range(1, len(s)):
        if s[i]>= fin:
            print (i)
            fin = f[i]
start  =  [1, 3, 0, 5, 8, 5]
finish =  [2, 4, 6, 7, 9, 9]    
activity(start, finish)    


0
1
3
4


In [29]:
#Print asterisk in Y pattern across n lines
#n = no. of lines
n = 30
if n%2 == 0:
    m = n/2
else:
    m = (n -1)/2 
for i in range(0, n):
    for j in range(0,40):
        if j == 40/2 - m or j == 40/2 + m:
            print("*", end =" ")
        else:
            print(" ", end =" ")
    print(" ")
    if m != 0:
        m = m - 1
    

          *                                                           *          
            *                                                       *            
              *                                                   *              
                *                                               *                
                  *                                           *                  
                    *                                       *                    
                      *                                   *                      
                        *                               *                        
                          *                           *                          
                            *                       *                            
                              *                   *                              
                                *               *                                
                

In [41]:
#Given multiple numbers and a number n, the task is to print the remainder after multiply all the number divide by n
#arr = [99, 9, 5, 25, 35, 14] 
#n = 11

def remainder(arr, n):
    tot = 1
    for i in arr:
        if tot == 0:
            tot =1
        tot = tot * i
        tot = tot % n
        print(tot)
    print(tot)

arr = [99, 9, 5, 25, 35, 14] 
n = 11
remainder(arr, n)

0
9
1
3
6
7
7


In [3]:
#Given Elements in an array, convert into matrix. Check if elements are sufficient or not
import numpy as np
class Matrix():
    def __init__(self, l, b, elements):
        self.width = l
        self.height = b
        self.mat = [[0 for x in range(b)] for y in range(l)]
        if l*b != len(elements):
            print("add approriate numbe rof items")
        self.add(l, b, elements)
    
        
    def add(self, l , b, elements):
        i = 0
        for j in range(l):
            for k in range(b):
                self.mat[j][k] = elements[i]
                i = i + 1
        print(np.array(self.mat))
        
        
        
        
elements = [1,2,3,4,5,6]
a = Matrix(2, 3, elements)

elements = [1,2,3,4,5,6]
b = Matrix(3, 2, elements)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [2]:
#Generate Permutations
def permutation(lst):
    if len(lst) == 0:
        return []
 
    if len(lst) == 1:
        return [lst]
 
    l = []
    done = []
    # Iterate the input(lst) and calculate the permutation
    for i in range(len(lst)):
        m = lst[i]
        if m not in done:
            remLst = lst[:i] + lst[i+1:]
            done.append(m)
            # Generating all permutations where m is first
            # element
            for p in permutation(remLst):
                l.append([m] + p)
    return l


data = list('001')
for p in permutation(data):
    print(p)


['0', '0', '1']
['0', '1', '0']
['1', '0', '0']


In [7]:
#generate permutation where each place range is different and avoid sum = n using List Comprehension
n =2
perm = [[a,b,c] for a in range(0,2) for b in range(0,2) for c in range(0,3) if a + b + c != n ]
print(perm)

[[0, 0, 0], [0, 0, 1], [0, 1, 0], [0, 1, 2], [1, 0, 0], [1, 0, 2], [1, 1, 1], [1, 1, 2]]


In [18]:
if __name__ == '__main__':
    n = int(input())
    arr = map(int, input().split())
    arr = list(arr)
    if n >= 2 and n <= 10 and min(arr) >= -100 and max(arr) <= 100:
        max_1 = arr[0]
        max_2 = arr[0]
        for i in range(1, len(arr)):
            if max_1 < arr[i]:
                max_2 = max_1
                max_1 = arr[i]
        print(max_2)
            

5
1 2 3 4 5
4


In [15]:
lst = [2, 3, 4, 5, 6]
print(max(lst))

6
