In [9]:
#Find Max in a 2-D List
arr = [[0, 0, 1, 5, 0, 1], [0, 1, 2, 2, 0, 0], [0, 5, 2, 0, 0, 1], [0, 1, 0, 3, 8, 0], [9, 0, 3, 0, 4, 0]]
print(list(map(max, arr)))
print(max(map(max, a)))

[5, 2, 5, 8, 9]
4


In [2]:
#Initializing a 2-D List with 0
import numpy as np
arr = [[0 for i in range(0,4)] for i in range(0,4)]
print(np.array(arr))

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [10]:
#Rounding of a number
a = 4.34
b = 5.67
print(round(a))
print(round(b))

4
6


In [11]:
#Copying array to another
a = [1,2,3,4,5]
#to copy with reference- changes in a wont impact b
b = a[:]
b[0] = 5
print("a=",a)
print("b=",b)

a= [1, 2, 3, 4, 5]
b= [5, 2, 3, 4, 5]


[['0', '0', '0'], ['0', '0', '1'], ['0', '1', '0'], ['1', '0', '0'], ['0', '1', '1'], ['1', '0', '1'], ['1', '1', '0'], ['1', '1', '1'], ['0', '1', '2'], ['1', '0', '2']]


[0, 1]
