In [5]:
#Find Max in a 2-D List
arr = [[0, 0, 1, 5, 0, 1], [0, 1, 2, 2, 0, 0], [0, 5, 2, 0, 0, 1], [0, 1, 0, 3, 8, 0], [9, 0, 3, 0, 4, 0]]
print(list(map(sum, arr)))
print(list(map(max, arr)))
print(max(map(max, arr)))

[7, 5, 8, 12, 16]
[5, 2, 5, 8, 9]
9


In [2]:
#Initializing a 2-D List with 0
import numpy as np
arr = [[0 for i in range(0,4)] for j in range(0,3)]
print(np.array(arr))

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [10]:
#Rounding of a number
a = 4.34
b = 5.67
print(round(a))
print(round(b))

4
6


In [11]:
#Copying array to another
a = [1,2,3,4,5]
#to copy with reference- changes in "a" wont impact "b"
b = a[:]
b[0] = 5
print("a=",a)
print("b=",b)

a= [1, 2, 3, 4, 5]
b= [5, 2, 3, 4, 5]


In [8]:
#Sort and print elements of an array
#* symbol is use to print the list elements in a single line with space#
lst = ['Harry', 'Berry']
a = sorted(lst, reverse=True)
print(*a, sep="\n")

Harry
Berry


In [12]:
#Printing upto 2 decimal places
a = 2.3456
print("{:.2f}".format(a))
print(round(a, 2))

2.35
2.35


In [3]:
for i in range(4):
    print("Value of i=",i)
    i += 1

Value of i= 0
Value of i= 1
Value of i= 2
Value of i= 3


In [7]:
#'str' object does not support item assignment
s = "This is an example"
print(s[5])
#s[5] = "h"
print(s[5])
#Convert string to list and than join back
listS = list(s)
listS[5] = "h"
print("".join(listS))

i
i
This hs an example


In [5]:
#Convert a list of characters into a string
s = ['a', 'b', 'c']
print("".join(s))

abc


In [8]:
import numpy as np
a = np.array([2, 5, 1, 8, 3])
a.argsort()[: 2]

array([2, 0], dtype=int64)

In [2]:
pairs = []
pairs.append(list((1,2)))
print(pairs)

[[1, 2]]


In [4]:
#Print in reverse order
a = [1,2,2,4]
for i in reversed(a):
    print(i)
for i in range(len(a)-1, -1, -1):
    print(a[i])

4
2
2
1
4
2
2
1


In [11]:
#Sort a list according to the second element in sublist
a = [["Ram", "shyam@gmail.com"], ["Shyam", "ram@gmail.com"], ["Ghanshyam", "zebra@gmail.com"]]
print(sorted(a, key=lambda x: x[1]))

[['Shyam', 'ram@gmail.com'], ['Ram', 'shyam@gmail.com'], ['Ghanshyam', 'zebra@gmail.com']]


In [12]:
#Bitwise AND operator
a = 2
b = 3
print(a & b)

2


In [1]:
#Accessing key and value both
dictNames = {'Ram' : 25, 'Shyam': 50}
for key, value in dictNames.items():
    print(key, value)

Ram 25
Shyam 50


In [4]:
arr = [[1,1], [1,2]]
arr[1][1].append(2)
arr[1]

AttributeError: 'int' object has no attribute 'append'